export const ALBUM_ERROR = 'ALBUM_ERROR';
export const ALBUM_LOADED = 'ALBUM_LOADED';
export const ALBUM_LOADING = 'ALBUM_LOADING';

export const ARTIST_ERROR = 'ARTIST_ERROR';
export const ARTIST_LOADED = 'ARTIST_LOADED';
export const ARTIST_LOADING = 'ARTIST_LOADING';

export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SEARCH_ALBUMS_ERROR = 'SEARCH_ALBUMS_ERROR';
export const SEARCH_ALBUMS_SUCCESS = 'SEARCH_ALBUMS_SUCCESS';
export const SEARCH_LOADING = 'SEARCH_LOADING';

export const SEARCH_ARTISTS_ERROR = 'SEARCH_ARTISTS_ERROR';
export const SEARCH_ARTISTS_SUCCESS = 'SEARCH_ARTISTS_SUCCESS';
export const SEARCH_ARTISTS_LOADING = 'SEARCH_ARTISTS_LOADING';

export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
