export const ALBUM_ERROR = 'ALBUM_ERROR';
export const ALBUM_LOADED = 'ALBUM_LOADED';
export const ALBUM_LOADING = 'ALBUM_LOADING';

export const ARTIST_ERROR = 'ARTIST_ERROR';
export const ARTIST_LOADED = 'ARTIST_LOADED';
export const ARTIST_LOADING = 'ARTIST_LOADING';

export const SEARCH_ALBUMS_ERROR = 'SEARCH_ALBUMS_ERROR';
export const SEARCH_ALBUMS_SUCCESS = 'SEARCH_ALBUMS_SUCCESS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
